enum AccountAccessLevel {
  ACCOUNT_ACCESS_LEVEL_NO_ACCESS = 'ACCOUNT_ACCESS_LEVEL_NO_ACCESS',
  ACCOUNT_ACCESS_LEVEL_READ_ONLY = 'ACCOUNT_ACCESS_LEVEL_READ_ONLY',
}

export default AccountAccessLevel;
